language: elixir
cache:
  directories:
  - deps
services:
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
script:
  # Install dependencies
  - "mix deps.get"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - "mix coveralls.travis"
  # Run static code analysis
  - "mix credo"
